pacman_vision: {
                enable_estimator: false, 
                enable_tracker: false, 
                enable_broadcaster: false,
                enable_listener: false, 
                point_cloud_resolution: 0,
                keep_organized: false,
                passthrough: true,
                pass_xmax: 0.5,
                pass_xmin: -0.5,
                pass_ymax: 0.5,
                pass_ymin: -0.5,
                pass_zmax: 2.0,
                pass_zmin: 0.2,
                downsampling: false, 
                leaf_size: 0.005,
                plane_segmentation: false,
                plane_tolerance: 0.005,
                listener_crop_right_arm: false,
                listener_crop_leftt_arm: false,
                listener_crop_right_hand: false,
                listener_crop_left_hand: false,
                estimator_clus_tol: 0.05,
                estimator_iterations: 5,
                estimator_neighbors: 10,
                estimator_object_calibration: false,
                broadcaster_rviz_markers: false, 
                broadcaster_tf: false, 
                tracker_estimation_type: 0,
                }
