pacman_vision: {
                enable_estimator: false, 
                enable_tracker: false, 
                enable_broadcaster: true,
                enable_listener: false, 
                point_cloud_resolution: 1,
                keep_organized: false,
                passthrough: true,
                pass_xmax: 0.4,
                pass_xmin: -0.4,
                pass_ymax: 0.4,
                pass_ymin: -0.4,
                pass_zmax: 1.5,
                pass_zmin: 0.2,
                downsampling: false, 
                downsample_leaf_size: 0.005,
                plane_segmentation: false,
                plane_tolerance: 0.005,
                crop_right_arm: false,
                crop_leftt_arm: false,
                crop_right_hand: false,
                crop_left_hand: false,
                use_table_transform: false,
                cluster_tol: 0.05,
                iterations: 10,
                neighbors: 10,
                object_calibration: false,
                estimated_objects: false,
                passthrough_limits: true,
                tracker_bounding_box: false,
                publish_tf: false, 
                estimation_type: 0,
                tracker_disturbance: false,
                }
